Apasch22/WebDev3

Version1.0/webDevUser06.html
Changes to name and date as well as introductory landing page
=> V1.0 User#06

Version1.0/webDevUser04.html
=> V1.0 User 04

Version1.0/webDevUser12.html
=> Did the funny and added my name

Version1.0/webDevUser05.html
=> WebDevUser16

Version1.0/webDevUser19.html
=> V1.0 User 19

Version1.0/webDevUser232641.html
=> V1.0 Max Brook

Version1.0/webDevUser08.html
=>  webDevUser08

Version1.0/webDevUser04.html, Version1.0/webDevUser24.html
=> WebDevUserTrustin24.html

Version2.0/webDevUser12.html
Updating my website to comply with 1.2a
=> Web Dev 1.2 a

Version2.0/webDevUser04.html
Creating a pull request for lesson 1.2a
=> Version 2.0

Version2.0/webDevUser04.html
These are the changes I made to my code.
=> Version 2.0 lesson 1.2b

Version2.0/webDevUser13.html
Added a banner and a smiley face. Used generic and non-generic containers.
=> Version 2 4/19/22

Version2.0/webDevUser04.html
This is the updated code for my "what used to be" smiley face.
=> Updated version 2.0 lesson 1.2b

Version2.0/webDevUser27.html
=> WebDev3 #27

Version2.0/webDevUser12.html
1.2b assignment hahah hehehaha
=> Yo mama! 1.2B

Version3.0/user06/music.html
Modified list to 5 of my own favorite songs with an intentionally broken file path to demonstrate alt
=> Create music.html (User06)

Version3.0/user27/aboutMe.html
=> About me . html 

Version4.0/user18/CSS/rainbow.css, Version4.0/user18/CSS/style.css, Version4.0/user18/display.html, Version4.0/user18/index.html, Version4.0/user18/portfolio.html
=> user 18 portfolio

Version4.0/user06/CSS/rainbow.css, Version4.0/user06/CSS/style.css, Version4.0/user06/display.html, Version4.0/user06/index.html, Version4.0/user06/portfolio.html
Update index.html, style.css; create display.html, rainbow.css, portfolio,html
=> Activity 1.4abc - User06

Version4.0/user15/CSS/rainbow.css, Version4.0/user15/CSS/style.css, Version4.0/user15/display2.html, Version4.0/user15/portfolio.html
=> user 15 Devan Gorham

Version5.0/user04/bootstrap.html, Version5.0/user04/confirmation.html
I did the correct thing for the 1.5a lesson
=> Version 5.0

Version3.0/user27/aboutMe.html, Version4.0/user27/CSS/rainbow.css, Version4.0/user27/CSS/style.css, Version4.0/user27/display.html, Version4.0/user27/index.html, Version4.0/user27/portfolio.html
=> >My Work as a Web Developer

Version5.0/user04/bootstrap.html
I added my footer to my code so you can see some cool pictures and the people who created it.
=> Added footer

Version5.0/user19/bootstrap.html, Version6.0/user19/CSS/style.css, Version6.0/user19/images/games.html, Version6.0/user19/index.html
=> did 1.6 and 1.5

Version6.0/user06/CSS/style.css, Version6.0/user06/games.html, Version6.0/user06/index.html, Version6.0/user06/script.html
=> Compare with Mackie

Version6.0/user16/script.html
=> Compare with kevincompare with kevin

Version6.0/user04/script.html
I finished all 8 of the elements for the script.html.
=> I did the 8 elements for my script

Version7.0/user15/About-the-sports-I-play.html, Version7.0/user15/CSS/style.css, Version7.0/user15/Cars.html, Version7.0/user15/JS/SampleJS.js, Version7.0/user15/Random-Stuff.html, Version7.0/user15/index.html, Version7.0/user15/my-favorite-dogs.html, Version7.0/user16/index.html
=> creating our own website

Version7.0/user04/fft.html, Version7.0/user04/jquery10.html, Version7.0/user04/jquery11-12.html, Version7.0/user04/jquery14.html, Version7.0/user04/jquery17.html, Version7.0/user04/jquery18.html, Version7.0/user04/jquery6.html, Version7.0/user04/jquery7.html, Version7.0/user04/jquery8.html, Version7.0/user04/paralax.html, Version7.0/user04/slider.css, Version7.0/user04/slider.js
I finally did the pull request for everything.
=> This is the pull request for a ton of stuff

Version3.0/user29/About_me.html, Version3.0/user29/CSS/sample.css, Version4.0/user29/CSS/style.css, Version4.0/user29/index.html
=>  there are the buttons and other stuff I copied and pasted.

Version7.0/user19/2022Roster.html, Version7.0/user19/Pride.html, Version7.0/user19/index.html, Version7.0/user19/jquary18.html, Version7.0/user19/jquery19.html, Version7.0/user19/jquery23.html, Version7.0/user19/jquery6.html, Version7.0/user19/jquery7.html, Version7.0/user19/load.php, Version7.0/user19/save.php
=> jquery and stuff
